media: public/img
content:
  - name: posts
    label: Posts
    type: collection
    path: content/blog
    view:
      fields: [ title, type, status, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: type, label: Type, type: select, default: article, options: {values: [ article, page, link, poem ]} }
      - { name: status, label: Status, type: select, default: draft, options: {values: [ draft, review, published, archived ]} }
      - { name: date, label: Date, type: date }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }
  - name: about
    label: About page
    type: file
    path: content/about/index.md
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, label: Key, type: string }
          - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
  - name: metadata
    label: Metadata
    type: file
    path: _data/metadata.js
    format: code
